<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>nuel</RootNamespace>
		<Version>5.2.1</Version>
		<Company>nuel</Company>
		<Product>Db</Product>
		<Authors>Ako Mahmoodi</Authors>
		<PackageId>nuel_Db</PackageId>
		<RepositoryUrl>https://github.com/pellk/Db</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>SQL Server, JSON, CSV</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Db.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
